fmnist: 
  dataset_name: fmnist
  img_size: 28
  channels: 1
  n_classes: 10 
  latent_dim: 100
  lr: 0.0002
  n_epochs: 120
  num_distill_epochs: 120
  batch_size: 64
  sample_interval: 800
  lambda: 100 
  temperature: 4

cifar10:
  dataset_name: cifar10
  img_size: 32
  channels: 3 
  n_classes: 10 
  latent_dim: 32
  lr: 0.0002
  lambda: 100 
  temperature: 4
  n_epochs: 200
  num_distill_epochs: 200
  batch_size: 64
  sample_interval: 800
  lambda: 0.1
  