fmnist:  
  dataset_name: fmnist
  img_size: 28
  channel: 1
  n_classes: 10
  lr_img: 0.1
  lr_net: 0.01
  batch_size: 256
  eval_train_epochs: 300 
  distillation_steps: 1000
cifar10: 
  dataset_name: cifar10
  img_size: 32
  channel: 3
  n_classes: 10
  lr_img: 0.1
  lr_net: 0.01
  eval_train_epochs: 300 
  batch_size: 256
  distillation_steps: 1000
