fmnist:  
  dataset_name: fmnist
  img_size: 28
  channel: 1
  n_classes: 10
  lr_img: 0.1
  lr_net: 0.01
  network_step: 20
  batch_size: 256
  eval_train_epochs: 300 
  network_step: 20
  dsa: null
  dsa_strategy: color_crop_cutout_flip_scale_rotate
  distillation_steps: 20000
cifar10: 
  dataset_name: cifar10
  img_size: 32
  channel: 3
  n_classes: 10
  lr_img: 0.1
  lr_net: 0.01
  network_step: 30
  eval_train_epochs: 300 
  batch_size: 256
  network_step: 30
  dsa: null
  dsa_strategy: color_crop_cutout_flip_scale_rotate
  distillation_steps: 20000